### ISSUE TITLE
Cloud Equivalence Considerations "Editorial"

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#103]
In general, products must be tested individually on each desired cloud service offering.
**NEW**
_Common Criteria is about products not systems or services. This guidance operates on the principle that_ products must be tested individually on each desired cloud service offering.

The Cloud Service Offering (to include cloud region or datacenter) must be detailed in the TOE
evaluated configuration details.
**NEW**
_When writing Security Targets,_ the Cloud Service Offering (_including the_ cloud region or datacenter) must be detailed in the TOE
evaluated configuration details.

CSOs can not inherently be assumed to be equivalent.
**NEW**
CSOs cannot inherently be assumed to be equivalent.

CC Scheme policy may define acceptance criteria.
**NEW**
Each CC scheme has the option to define a policy for acceptance criteria.

**Comment by bharveyTX** [comment]
Changes implemented.
