### ISSUE TITLE
TOE is never defined

### ISSUE THREAD

**Issue by aws-brad** [CC-in-the-Cloud/Admin#105]
I was scanning the guidance and just realized, we never actually define the term "TOE"

Propose that under the first use which is hosting environment, we properly spell out the acronym for first use. 
 TOE boundary and is equivalent to the CC term "Operational Environment."
to 
Target of Evaluation (TOE) boundary and is equivalent to the CC term "Operational Environment."

**Comment by jgb1128** [comment]
https://www.commoncriteriaportal.org/files/ccfiles/CC2022PART1R1.pdf, page 33.

5.3 Target of evaluation (TOE)
5.3.1 General
The CC is flexible in what is evaluated and is therefore not tied to the boundaries of IT products
as commonly understood. Therefore, in the context of evaluation the CC uses the term “TOE”
(Target of Evaluation).
While there are cases where a TOE consists of a complete IT product, this need not be the case.
The TOE may be an IT product, a part of an IT product, a set of IT products, a unique technology
that can never be made into a product, or a combination of these.
As far as the CC is concerned, the precise relation between the TOE and any IT products is only
important in one aspect: the evaluation of a TOE containing only part of an IT product should not
be misrepresented as the evaluation of the entire IT product.
EXAMPLE Examples of TOEs include devices characterized by few interfaces, reduced attack surface,
and a well-known supply chain:
— a network device;
— a software application;
— an operating system;
— a virtualization system;
— an integrated circuit;
— the cryptographic co-processor of an integrated circuit;
— an application for a mobile device;
— a database application excluding the remote client software normally associated with that database
application.
TOEs can also be more complex, characterized by a large interface/large interfaces and/or number of
components, multiple manufacturing/integration phases, field upgradeable products such as:
— a Local Area Network (LAN) including all terminals, servers, network equipment and software;
— a mobile device;
— gateways and hubs;
— a software application in combination with an operating system;
— a multi-function device, such as a multi-function printer;
— a Hardware Security Module (HSM).

@bharveyTX will you figure out how to integrate?  I'm on the fence if it needs to be in the glossary or just spelled for first use.

**Comment by jgb1128** [comment]
Suggestion for week of Aug 21:  refine definition for TOE in the context of a cloud evaluation; add to glossary. Reference CC p1 for backup.

**Comment by bharveyTX** [comment]
We have added a new section "Relationships Between the Trusted Platform / TOE Platform, and TOE" to explain the distinctions between the three concepts and provided examples. This section will need editorial.

**Comment by jgb1128** [comment]
Editorial to be cleaned up:
"Relationships Between the Trusted Platform / TOE Platform, and TOE
We need to explain that the Trusted Platform exists underneath the TOE Platform and is provided by the CSP.

The TOE Platform may or may not exist on top of the Trusted Platform, but is specifically what is providing functionality to the TOE.

If the TOE Platform does not exist as the TOE is capable of meeting all PP SFRs independently, then a Trusted Platform would still be needed to provide a hosting environment for the TOE.

For example, for a TOE that is a Software Application, the TOE Platform would be the Operating System and the Trusted Platform would be the underlying virtualization solution provided by the CSP.

If the TOE is a General Purpose Operating System (GPOS) then the TOE Platform would be the underlying hypervisor and the Trusted Platform would include the hardware layer and below from the CSP.

If the TOE is a General Purpose Compute Platform (GPCP) then no TOE Platform is applicable and the Trusted Platform would be the power, cooling, and physical security provided by the CSP." For Anne Gugel

**Comment by jgb1128** [comment]
Closed this is now incorporated.
