### ISSUE TITLE
Insider threat ESR statement 

### ISSUE THREAD

**Issue by mmbarry** [CC-in-the-Cloud/Admin#11]
Perhaps, wrt the ESR and Insider Threat, we need only identify the need to expand to scope of the threat as presented for On Prem products to also include the Cloud Service. 
For example, “While the Common Criteria for On Prem products addresses Insider Threats at certain levels of assurance and only with respect to the product vendor and the customer, CC in the Cloud needs to extend such attention, advice, and/or requirements to include the Cloud provider.” 
 
This could be done without offering any solutions in the ESR and so t would simply state that it’s a probable issue that the iTC will address.

**Comment by bharveyTX** [comment]
Closed as per WG discussion.
