### ISSUE TITLE
guidance doc organization note - PP cloud adaptation process needs material on what may be added by cloud evals

### ISSUE THREAD

**Issue by jfisherbah** [CC-in-the-Cloud/Admin#110]
When the materials for incorporating cloud materials into PPs is added to the guidance document, it is recommended for those materials to reference the "Suggested inputs to a Security Problem Definition for Cloud evaluations" section of the guidance doc.

The MDM PP pilot was only concerned with adapting the existing PP materials into cloud so it did not consider whether any cloud-specific threats, assumptions, objectives, or SFRs should be added, either product-specific or things that could be universally applicable to cloud products.

So there is currently a gap for "what new things would a PP need to **add** to accommodate cloud evaluations. The SPD materials partially address that, but we would also need to consider whether those would tie back to new cloud-specific threats (or just existing ones), and whether there are any cloud-specific TOE objectives or SFRs that would need to be considered.

**Comment by jgb1128** [comment]
Reference as an appendix.  Noted by Jade this was a part of the first phase and at this writing it is not confirmed that the MDM PP has sufficient SARs and SFRs for cloud based evaluations.
