### ISSUE TITLE
CCiTC Guidance for Cloud Evals Minor feedback/suggestions

### ISSUE THREAD

**Issue by compgeeksquires** [CC-in-the-Cloud/Admin#112]
Software as a Service (SaaS)
Add "Software as a Service (SaaS)." to beginning of the section match other sections.

Shared Security Model
If the NDcPP is just an example here, need to say that. It looks like we're suggesting it is the only one that would need to change.

Shared Security Model
"It is also expected that there will be evaluations of TOEs that are integral to a CSPs cloud stack from hardware to application layers." What does this sentence mean? That  the CSP stack itself will be validated?

CPU Equivalency
This first sentence doesn't say why it is important. The rest of the section points to it being necessary for cryptographic claims. Is it important for any other reasons?

Process to optimize a PP for TOEs in a cloud environment. 
Process Overview
"Identify SFR challenges in a cloud operational environment" bullets: This is not an SFR challenge. This is just a challenge with testing the SFR. The SFR could still be met by the TOE but just not be able to be tested in the same way. Are there any SFR challenge examples, like FAU_GEN in earlier sections where the TOE and the CSP split meeting the requirement. We should have a section for both SFR challenges and SFR Testing Challenges.

Process to optimize a PP for TOEs in a cloud environment. 
Security Problem Definition
"Generally within the PP’s proposed, the Network Device and Application Software PPs are used the most." This sentence is out of place and largely implied elsewhere in the document.

Process to optimize a PP for TOEs in a cloud environment. 
Security Requirements
Typo: "Others example" -> "Other examples"

**Comment by bharveyTX** [comment]
We also need to add a TOE labeling example to the guidance. 

Let's also include an example for how SFRs must be modified in the SFR challenges section to distinguish between SFR challenges and SFR testing challenges.

**Comment by tsc-n** [comment]
"Software as a Service (SaaS)" section

2nd paragraph: add "and"
- before: "... above use case: cPP_App_SW, cPP_DBMS, PP_MDM."
- after: "... above use case: cPP_App_SW, cPP_DBMS, and PP_MDM."

3rd paragraph: add comma after "baseline"
- before: "... were to be used as a baseline the cloud extensions ..."
-  after: "... were to be used as a baseline, the cloud extensions ..."

**Comment by tsc-n** [comment]
"Platform as a Service (PaaS) section

2nd paragraph
- before: "... above use case: PP_OS, cPP_ND"
-  after: "... above use canse: PP_OS and cPP_ND."

**Comment by tsc-n** [comment]
"Shared Security Module" section

1st paragraph, 2nd sentence
- before: "This model acknowledges that while the CSP is responsible for securing the underlying cloud infrastructure, and the customer bears the responsibility of securing their applications, data, and configurations within that infrastructure based on the service model."
- suggested change: "This model acknowledges that the CSP is responsible for securing the underlying cloud infrastructure and that the customer bears the responsibility of securing their applications, data, and configurations within that infrastructure based on the service model."

**Comment by tsc-n** [comment]
"Responsibilities" section

1st paragraph, last sentence
- typo: change "(TOE latform)" to "(TOE platform)"

**Comment by tsc-n** [comment]
"Guidance Documentation" section

3rd paragraph, 1st sentence
- before: "... which are taylored to evaluators limited knowledge ..."
-  after: "... which are taylored to the evaluator's limited knowledge ..."

**Comment by tsc-n** [comment]
"Relationships Among the TOE, TOE platform, and the Trusted Platform" section

2nd paragraph, 2nd sentence
- before: "... will require a hosting environment provide by the trusted platform."
-  after: "... will require a hosting environment provided by the trusted platform."

**Comment by tsc-n** [comment]
"Scheme Guidance" section

2nd paragraph, 2nd sentence
- before: "... of the perational environment of the PP."
-  after: "... of the operational environment of the PP."

3rd paragraph, 2nd sentence
- before: "... thereby maintaing the integrity of results."
-  after: "... thereby maintaining the integrity of results."

**Comment by tsc-n** [comment]
"Guidance for Evaluators" section
1st paragraph, 1st sentence
- before: "... clear explanations tailored to evaluators perhaps limited ..."
-  after: "... clear explanations tailored to an evaluator's perhaps limited ..."

**Comment by tsc-n** [comment]
"TOE Identification" section
- Are the AWS example links missing?

**Comment by tsc-n** [comment]
"Protection Profile Considerations" section
1st paragraph, 1st sentence
- before: "... for adapting CCiTC methodology ..."
-  after: "... for adapting CCitC methodology ..."

"Create and Outline for Mapping" subsection
1st paragraph, 1st sentence
- were "SFRs, Assumptions, SARS" meant to be formatted as a list?

**Comment by ecbconnor** [comment]
> "Guidance Documentation" section
> 
> 3rd paragraph, 1st sentence
> 
>     * before: "... which are taylored to evaluators limited knowledge ..."
> 
>     * after: "... which are taylored to the evaluator's limited knowledge ..."

Spelling is "tailored" not "taylored"

**Comment by bharveyTX** [comment]
All changes have been implemented.
