### ISSUE TITLE
Shared Security Model

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#115]
For example....in paragraph 4.

**Comment by jgb1128** [comment]
Reference SFR and SAR to ISO document

**Comment by jgb1128** [comment]
Original:  To accommodate this scenario, the collaborative protection profile for the virtualized network
device on the public cloud should specify the requirements for log consumption from the CSP’s
logging infrastructure.

Change to To accommodate this scenario, the collaborative protection profile for the network
device on the public cloud should specify the requirements for log consumption from the CSP’s
logging infrastructure.

**Comment by jgb1128** [comment]
Change TOE Vendor to TOE developer in all cases

**Comment by jgb1128** [comment]
Replace TSS with ST as appropriate.  Last paragraph look at rewording to align with true CC

**Comment by GY5318** [comment]
In the Shared Security Model section and needed to break it up into the 3 types of TOEs involved to the security levels involved.  Below is what I wrote for the 3rd paragraph:

While the CSP maintains the security and availability of the TOE Platform, the TOE administrator (customer) is assumed to be tasked with safeguarding their applications, data, and configurations within the cloud environment for a SaaS. For PaaS and IaaS, the safeguarding extends into OS and hypervisor safeguarding controls.  For all cloud levels, the TOE administrator actively manages security controls, such as authentication mechanisms, encryption protocols, and network access policies, and others needed to overall protect their assets and mitigate potential risks.

**Comment by jgb1128** [comment]
Done.
