### ISSUE TITLE
Trusted Platform and TOE platform

### ISSUE THREAD

**Issue by GallagherTom** [CC-in-the-Cloud/Admin#116]
Currently, the doc does not allow for any overlap between the Trusted Platform and the TOE Platform. Because of this, the Trusted Platform (provided by the CSP) could not fulfill security requirements. We should think about whether or not this is a necessary separation

**Comment by jgb1128** [comment]
@GallagherTom is there a case where the TOE would fulfil SFRs from the operational environment?

**Comment by GallagherTom** [comment]
@jgb1128 I'm not sure I understand the question entirely, but I'll take a stab and let me know if I misunderstood. My concern is that any SFR's where "invoke platform-provided functionality" is selected would need to be met by the TOE Platform (which I believe was stated while discussing this during the workshop). If so, this would mean that the CSP environment would be unable to satisfy any platform requirements (such as cryptography) even if it is capable of doing so. I think the easiest resolution to this is by showing that the TOE platform can include parts of the Trusted Platform. I'm not aware of additional problems that creates but would be happy to discuss concerns that others have.

**Comment by jgb1128** [comment]
In the relationships between TOE, TOE Platform, and Trusted Platform section, add additional paragraph that instructs PP authors to refine selections that invoke platform functionality to consider the TOE Platform or Trusted Platform and how it will be utilized.

**Comment by bharveyTX** [comment]
Added the following language: 

Additionally, there may be such cases which may require PP authors to provide additional selections for invoking either the TOE Platform or the Trusted Platform for SFR enforcing functionality.

**Comment by bharveyTX** [comment]
Closed per discussion.
