### ISSUE TITLE
Threats in cloud operating environment

### ISSUE THREAD

**Issue by fahmed11** [CC-in-the-Cloud/Admin#117]
It appears that the following sentence in the 3rd para of "Suggested Inputs ..." section (page 24) need to be qualified a bit.
"A threat, as an adverse action performed by a threat agent on an asset, is not contextual to the operating environment of the TOE." While the notion is understandable, wouldn't cloud operating environment  potentially lead to additional threat vector/agent?

**Comment by jgb1128** [comment]
@fahmed11 do you have a suggested better wording to offer?

**Comment by jgb1128** [comment]
Fareed we will close this issue if you can't suggest another option.

**Comment by jgb1128** [comment]
Closing due to lack of actionable materials.
