### ISSUE TITLE
Deployment model

### ISSUE THREAD

**Issue by fahmed11** [CC-in-the-Cloud/Admin#118]
"However, CCiTC evaluations are not limited to a particular deployment model". [page 7, para 5]. The sentence reads well and conveys the intended message; however since the  'deployment model' is a bit loaded term in the context of Cloud, it could be confusing.

**Comment by jgb1128** [comment]
@fahmed11 do you have better wording to offer?

**Comment by jgb1128** [comment]
Please suggest new wording or we will close.

**Comment by jgb1128** [comment]
Closing due to lack of actionable materials.
