### ISSUE TITLE
resilience to underlying platform changes

### ISSUE THREAD

**Issue by kingoatsec** [CC-in-the-Cloud/Admin#12]
If the TOE must be resilient to underlying platform changes, does that not imply the TOE cannot use anything provided by a platform apart from generic CPU, memory management, and network services? A TOE depending on a specific platform API/library or hardware crypto implementation like AES-NI would fail when run on another host not providing the same service. Is this really a requirement on the TOE or should it be an assumption that the cloud service provider will deploy functionally equivalent platforms?

**Comment by bharveyTX** [comment]
Issue resolved during WG session.
