### ISSUE TITLE
Defer Scheme Advice and Lab Instructions?

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#122]
At the end of the meeting last week, Jade suggested we consider deferring the scheme advice and lab instructions so we can finish our guidance faster.  This is a major decision as these two pieces were considered early on critical parts of guidance. We will discuss and a vote may be necessary. #106 #104

**Comment by jgs1618** [comment]
Just to clarify, this is a NIAP suggestion. --Jade

**Comment by mbdowne** [comment]
The main point here is how long this is going to take. I thought the plan was to publish the first for public comment by the end of the year. How much longer will it take to incorporate this? Is the end of the year still doable? Is that no longer the plan? If not, what is the new estimate?

**Comment by jgb1128** [comment]
Initial sets of high level materials are now included.
