### ISSUE TITLE
Cloud Composition wording

### ISSUE THREAD

**Issue by heimannrj** [CC-in-the-Cloud/Admin#128]
The following is from the Cloud Composition section and after taking a fresh read of it, it seems confusing to me.

> When conducting Common Criteria evaluations for IT products in cloud environments, it is crucial to recognize that the Target of Evaluation (TOE) will often encompass products designed for the cloud's unique demands. In this context, the TOE is most likely to consist of products that are capable of "lifting and shifting," meaning they can seamlessly migrate and operate in cloud environments. These types of TOEs typically fall within the three primary cloud architecture models: Software as a Service (SaaS), Platform as a Service (PaaS), or Infrastructure as a Service (IaaS).

The first two sentences appear to be at odds with eachother. In my understanding, products designed for cloud are not typically lifted and shifted into place . I think of "Lift and shift" as more of a cloud migration strategy, not a deployment model in and of itself. I am not so sure so many TOEs will fall into this catagory. If we think they will, we should discuss some verbiage to explain why.  Otherwise, it may be better to stay focused on the deployment models which will be more enduring.  Offer the following alternate language:

> When conducting Common Criteria evaluations for IT products in cloud environments, it is crucial to recognize that the Target of Evaluation (TOE) may be presented in a variety of deployment models.  TOE products can be specifically designed to operate within the cloud natively, utilizing services and constructs that are only available within the cloud environment.  They can also be deployed as self-contained products that are simply hosted on cloud infrastructure, also known as “lift and shift”.  They may be a hybrid of both methods. The TOE will typically fall within the three primary cloud architecture models: Software as a Service (SaaS), Platform as a Service (PaaS), or Infrastructure as a Service (IaaS).

**Comment by jgb1128** [comment]
Accepted as below.

When conducting Common Criteria evaluations for IT products in cloud environments, it is crucial to recognize that the Target of Evaluation (TOE) may be presented in a variety of deployment models. TOE products can be specifically designed to operate within the cloud natively, utilizing services and constructs that are only available within the cloud environment. They can also be deployed as self-contained products that are simply hosted on cloud infrastructure, also known as “lift and shift." They may be a hybrid of both methods. The TOE will typically fall within the three primary cloud architecture models: Software as a Service (SaaS), Platform as a Service (PaaS), or Infrastructure as a Service (IaaS).

**Comment by bharveyTX** [comment]
Change implemented.

**Comment by bharveyTX** [comment]
Closed per discussion.
