### ISSUE TITLE
editorial comments on guidance doc

### ISSUE THREAD

**Issue by jfisherbah** [CC-in-the-Cloud/Admin#137]
Some suggestions for editorial changes and internal consistency in the Guidance Doc are in the following document for consideration:

[Guidance Document Notes.docx](https://github.com/CC-in-the-Cloud/General/files/14104997/Guidance.Document.Notes.docx)

**Comment by jgb1128** [comment]
re: "The graphic is very blurry" I would be more than happy for someone to come up with a new graphic.  Any volunteers?

**Comment by jhonkofsky** [comment]
I created this.
<img width="447" alt="CCitC Graphic_JAH" src="https://github.com/CC-in-the-Cloud/General/assets/94634298/0751bea0-bf4e-4a54-8477-5b8dede625d7">

**Comment by bharveyTX** [comment]
I attempted to make a vectored logo for easier scaling also: 

![CCiTCLogo](https://github.com/CC-in-the-Cloud/General/assets/64159025/ad62cf45-dd1f-43be-8305-12f3d89544d3)

**Comment by tstodart** [comment]
![CCitCLogoidea](https://github.com/CC-in-the-Cloud/General/assets/78868132/10c0c640-b77b-4ead-9fc2-6d497a4b205c)
Just an idea (based on Brandon's work)

**Comment by bharveyTX** [comment]
All changes have been implemented.
