### ISSUE TITLE
For completeness, add Google to TOE identification section

### ISSUE THREAD

**Issue by jgs1618** [CC-in-the-Cloud/Admin#143]
The document contains examples from 3 of the 4 major Cloud providers: AWS, Azure and Oracle.  I think it would be more complete to have Google in this section as well.

**Comment by jgs1618** [comment]
2/28/2024 - Contacted a Google participant in ISO/IEC SC38 Cloud Computing to see if she could find someone at Google to fill out this section.

**Comment by jgb1128** [comment]
For now waiting for Google instructions...then revisit.

**Comment by jgb1128** [comment]
Jade will go back and ask for instructions. Once received we will look to incorporate.

**Comment by jgb1128** [comment]
Continuing to track, no response yet from Google.

**Comment by jgb1128** [comment]
Google is not interested in providing this information so we are closing this issue.
