### ISSUE TITLE
Tyrone Stodart Edits

### ISSUE THREAD

**Issue by tstodart** [CC-in-the-Cloud/Admin#15]
In "Analysis is Static" section second Para, "cloud certifications would require.." should start with a capital letter.
In the same sentence not so sure about the term 'quickly perishable'. Perhaps the terms "transitory" or "ephemeral" might be more suitable or more explicitly "subject to frequent revisions".

Similarly, in the first sentence of the section "Environmental Evolution", the use of the term 'half-lives' in the first sentence I think could be improved (I am not sure vendors want to suggest their environments are degrading to 50% over time). I guess 'shelf-life' is a common term but perhaps this sentence can be fleshed out a little e.g. "Cloud environments are evolving as routine in order to provide new services and greater efficiencies to customers".

**Comment by bharveyTX** [comment]
Changes implemented.
