### ISSUE TITLE
German Scheme Feedback:  Determine Appropriateness of Security Problem Definition

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#155]
Page 35, 2nd to last paragraph
"The decomposition and mappings done for this PP could potentially be usable in other PPs without needing to come up with separate
rationale for what is essentially the same process." _Maybe also add that the assumptions made in this MDM PP example could potentially be reused for other PPs._

**Comment by bharveyTX** [comment]
Additional language to include assumptions would be redundant, we feel there is sufficient context to draw this conclusion.
