### ISSUE TITLE
German Scheme Feedback:  Determine Appropriateness of Security Problem Definition

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#156]
Last paragraph of the subsection (top of page 36)
Responsibility for secure deployment and configuration of the TOE may involve collaboration of up to four different groups (infrastructure vendor, platform vendor, software vendor, and **end user**).

_For clarity and consistency it might be beneficial to use the term "TOE Admin" in this case as done before and after._

**Comment by bharveyTX** [comment]
Will change.

**Comment by bharveyTX** [comment]
Update Made
