### ISSUE TITLE
Cory C. Comments

### ISSUE THREAD

**Issue by ClarkCP** [CC-in-the-Cloud/Admin#16]
- Wrt Assumptions.  What about Data Sovereignty?  This is a fairly big concern for government organizations, although it might be beyond the scope of this.
- Wrt Trusted provider/Admin.  What about assessments vs. authorizations?  for example the CCCS has an area that provides assessments of cloud services, but to call them authorizations might be a stretch.

**Comment by bharveyTX** [comment]
Changes implemented.
