### ISSUE TITLE
German Scheme Feedback:  Map to Other Applicable Cloud Programs

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#160]
First paragraph, see bolded text.
Once the assumptions for the TOE’s operational environment are mapped to the referenced cloud certification scheme to determine what can be considered a 'trusted platform' for the TOE, and the SFRs and SARs have been assessed to determine how cloud deployment affects the certification process. The output of this assessment can be mapped to **other** cloud certification programs.

_Do you mean other than FedRAMP?_

**Comment by bharveyTX** [comment]
The output of this assessment can be mapped to other cloud certification programs. -> The output of this assessment can be mapped to **various** cloud certification programs.

**Comment by bharveyTX** [comment]
Change implemented.
