### ISSUE TITLE
Preface changes:

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#17]
The CC in the Cloud WG is developing an Essential Security Requirements (ESR) that captures the
fundamental requirements. This initial draft contains material that was created by the WG as a
framework to utilize Common Criteria methodology for products deployed in a cloud environment.

change to:

The CC in the Cloud **Technical Work Group (TWG) i**s developing an Essential Security Requirements (ESR) that captures the
fundamental requirements **for evaluating products in the Cloud**. This initial draft contains material that was created by the **T**WG as a
framework to utilize Common Criteria methodolog**ies** for products deployed in a cloud environment.

**Comment by bharveyTX** [comment]
Change implemented.
