### ISSUE TITLE
Background and Purpose changes

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#18]
At some point customers are going to recognize that a CC evaluation of an **Information Communication Technologies (ICT)** product provides
little assurance in a cloud environment. Without a plan for CC addressing this factor, CC will
become irrelevant in DevOps and **c**ustomers will require additional country specific testing
instead.
As the market moves to **such** cloud-based solutions, ISO/IEC15408 should be adapted in order to provide
security assurance for cloud scenarios. In addition, vendors of products to be evaluated along with
authors of cPP’s aimed at cloud use case evaluations, may need to add or alter specific code or cPP
content carefully to ensure evaluate-able products and cPP’s.
Use Cases

**Comment by bharveyTX** [comment]
Changes implemented.
