### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#19]
Use Case 2: Platform as a service (PaaS) **(or application platform as a service (aPaaS) or platform based
service)** is a category of cloud computing services that provides a platform allowing
customers to develop, run, and manage applications without the complexity of building and
maintaining the infrastructure typically associated with developing and launching an app.

_We could consider the alternatives as a footnote_

**Comment by bharveyTX** [comment]
Change implemented. Added comment to review other sources for use case definitions.
