### ISSUE TITLE
Platform Abstraction

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#21]
Existing TOE composition requires stability in both the TOE and TOE Platform. The TOE operating
environment in a cloud use case may or may not change dramatically due to a variety of factors
such as hardware deprecation, underlying firmware updates, OS changes, etc. These changes may
or may not be detected by the TOE and may or may not affect the TOE security posture.
New methodology to address minimum satisfactory capabilities in this regard will be needed to
bridge this gap **such as a Trusted Platform scheme**.

**Comment by bharveyTX** [comment]
Change implemented.
