### ISSUE TITLE
Roger's addition to summary

### ISSUE THREAD

**Issue by mmbarry** [CC-in-the-Cloud/Admin#24]
Suggesting the insertion in between paragraphs 2 and 3 of the summary - the following: 

It is the goal of the CCiTC WG to address the security concerns raised in this ESR, to examine and reference existing and developing processes and certifications that support extension of cPP’s and ST’s to include cloud usage and to identify CC requirements needed to gain or maintain such CC certifications. The WG intends to provide guidance as well as examples of specific wording that could be used in whole or in part by developers of cPP’s and ST’s. In addition, the WG intends to document any limitations found and may consider/present options for future changes.

**Comment by bharveyTX** [comment]
Change implemented.
