### ISSUE TITLE
CCiTC methodology

### ISSUE THREAD

**Issue by tbenkartidtec** [CC-in-the-Cloud/Admin#25]
Each of the Use Cases refers to "CCiTC methodology".  Was that terminology chosen deliberately, or (to be politically correct) should it be "CCTWG methodology"?

**Comment by jgb1128** [comment]
Actually Tom, CCiTC does not mean Common Criteria international Technical Community. That would be very generic group!  CCiTC stands for Common Criteria in the Cloud. Hope this helps. I do see the confusion however, and will look at possible alternatives.

**Comment by tbenkartidtec** [comment]
I thought it stood for CC in the Cloud iTC, so it's doubly confusing.  How about CCitC (lower case t) at minimum for a change?

Thanks.

Tom

**Comment by jgb1128** [comment]
I agree. @bharveyTX let's change this to CCitC

**Comment by bharveyTX** [comment]
Change implemented.
