### ISSUE TITLE
Modules?

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#26]
In order to become an iTC should we focus on creating modules?  We asked Matt Downey today and via Jade got this response:
"Matt thinks that producing modules for CC in the Cloud would satisfy the requirements for being an iTC per the discussed CCRA section.  He mentioned that another group is doing that."

**Comment by jgb1128** [comment]
We have essentially decided not to do modules.  Will look to close this issue at the workshop

**Comment by jgb1128** [comment]
To raise in the workshop:  Will the CCDB consider that creating "guidance" like JIL and this group have done, considering we have 3 sponsoring nations (all certifying) is possible for creating an iTC?

**Comment by mbdowne** [comment]
The CCDB already has a proposed agenda item to discuss this. 

Strongly recommend that the group focus on producing content and determine any other additional format later.

**Comment by jgb1128** [comment]
I am closing this issue today.  Our direction is not to create modules. Instead we are focused on guidance for PP authors and evaluators.
