### ISSUE TITLE
Remote testing--need NIAP to review

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#29]
Labgram 78 https://www.niap-ccevs.org/Documents_and_Guidance/labgrams/labgram.cfm?id=78 
specifies the rules for the location of testing. Cloud testing in it's nature will always be remote.

Policy as follows:
Testing Location

Testing at a vendor’s site is acceptable if the CCTL follows its procedures that conform to paragraphs 5.3.6 and 5.3.7 above.  The non-proprietary AAR must identify the procedures the lab followed in each specific instance to ensure the independence of the testing was not compromised. 

Remote testing is generally not acceptable.  It is very difficult for the CCTLs to ensure proper control over a remote test environment, and difficult for validators to ascertain if the proper control was maintained.  Therefore, remote testing or remote observation of testing being done by someone other than the evaluators is only acceptable on a CCEVS-approved case-by-case basis.

Need NIAP to propose new wording for remote testing policy for cloud evaluations. Our proposal would be that approved cloud evaluations always allow remote testing.

**Comment by jgb1128** [comment]
Suggestion from TP sub-group look at FedRamp rules for remote testing and see if adaptable for this project.

**Comment by mbdowne** [comment]
Current policy allows for it on a case by case basis. It cannot be as simple as "remote testing is allowed" as NIAP already has a process to ensure certain protections are in place before testing begins. That's required regardless of whether it's cloud or not.

**Comment by mbdowne** [comment]
NIAP labgram 78 and Section 2.2.1.b of NIAP's Publication 4 require all remote testing requests to be approved by NIAP in advance. NIAP is in the process of finalizing and formalizing its requirements for remote testing approval, which should cover everything here. Recommend closing this issue.

**Comment by jgb1128** [comment]
Closed for now.
