### ISSUE TITLE
Proposed definition for CSP in Guidance

### ISSUE THREAD

**Issue by tstodart** [CC-in-the-Cloud/Admin#31]
From https://cloudsecurityalliance.org/blog/2020/04/30/what-is-a-cloud-service-provider/
either
"A cloud service provider, or CSP, is a company that offers some component of cloud computing; typically infrastructure as a service (IaaS), software as a service (SaaS) or platform as a service (PaaS) to other businesses or individuals."
Or
“A Cloud Service is any system that provides on-demand availability of computer system resources, e.g; data storage and computing power, without direct active management by the user”
Second one more generic and probably more in-keeping with standards/ISO style

**Comment by jgb1128** [comment]
We went with the first one.
