### ISSUE TITLE
Define Trusted Provider

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#33]
To discuss and write up is what is a trusted provider? What is the criteria? What are the metrics? How is this decided? Etc.

**Comment by fahmed11** [comment]
Hope the answers to these questions will clarify the interrelation/dependencies of Trusted Platform and Trusted Provider. The particular question I have is -- does the criteria for trusted platform subsume the reqs on trusted provider?
 I am saying this from the perspective of how  FedRAMP articulates the requirements on cloud service provider (CSP), through the intake process for the authorization of the  cloud service offering (CSO) --  Part of the ‘Readiness Assessment Review’ of FedRAMP  aims at screening the provider, to sort of make sure behind every acceptable CSO, is an acceptable CSP.

**Comment by tsc-n** [comment]
Could the following serve as a starting point for the definition of a "trusted provider"?

A "Trusted Cloud Service Provider" (TCSP) is defined as a Cloud Service Provider (CSP) that (1) has undergone security validation by a recognized body (?) and that (2) offers customer access to those validated services and platforms that comprise the environment in which the TOE is operated.

**Comment by mbdowne** [comment]
Trusted provider definition from 7 September 2022 meeting: "A trusted provider provides a trusted platform."

**Comment by bharveyTX** [comment]
Closing as we have chosen not to incorporate the Trusted Provider concept at this time. We may revisit as needed in the future.
