### ISSUE TITLE
Trusted Provider--CAVP

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#34]
- Today's requirements: CPU, chip set,  O/S, hypervisor or container
- ID how variable the cloud platform could be for a live instance.
- Containers--how would that work? Look at NIST guidance
- How much control does the vendor have over what the platform looks like?

TOE vendor should ID what platforms are available?

This seems to be doable. Need to document instructions.

**Comment by jgb1128** [comment]
https://csrc.nist.gov/csrc/media/Projects/cryptographic-algorithm-validation-program/documents/CAVPFAQ.pdf
GEN.17 Does CAVP allow algorithm tests to be performed on a target operating system running on top of a virtual machine? Or must the target OS be the machine’s native OS? What about containers?
The CAVP allows algorithm tests to be performed on a guest operating system running on a hypervisor; however, the full virtualization environment shall be specified in the OE listing as described below.
For a Type 1 (or native) hypervisor, where the hypervisor runs directly on the hardware, the OE listing shall include the guest OS, hypervisor, and processor using the following format: “Guest OS on hypervisor on Processor.” An example is “Microsoft Windows 11 on VMWare ESXi 7.0 on Intel Xeon W (Rocket Lake).”
For a Type 2 (or hosted) hypervisor, where the hypervisor runs on a host operating system (OS), the OE listing shall include the guest OS, hypervisor, host OS, and processor using the following format: “Guest OS on hypervisor on Host OS on Processor.” An example is “Microsoft Windows 11 on Parallels Desktop 17 on

**Comment by jgb1128** [comment]
The cryptographic module under test SHALL be confirmed to be running on an OE that is well-defined and has a specific OS version, hardware platform and version, and processor (including microprocessor version), as shown on the module’s certificate and security policy and where this can be confirmed during the test session. A 3rd party cloud system (e.g., Amazon Web Services, Microsoft Azure, and Google Cloud) may be used if these rules are met and the operating environment provides the same or additional level of security as the lab would provide for internal testing.” (Above appears after “… controlled by the vendor.”  and before “The tester SHALL have control (oversight)…”}

**Comment by bharveyTX** [comment]
We have incorporated guidance for Algorithm testing and labeling in the CPU Equivalency section. As we are not using the trusted provider concept at this time I am closing this issue as resolved.
