### ISSUE TITLE
Equivalence

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#36]
Use Cases:
App level:  CSP A to CSP B same OE underlying is that equivalent?
O/S: does it require the same OE?

To discuss in Annapolis Junction:  testing on one CSP, can this be applied to other CSPs? What are the barriers? How to achieve? What are the steps? What arguments would be acceptable?

**Comment by bharveyTX** [comment]
We believe that, in general, products must be tested individually on each cloud platform. For example on Azure, On AWS, etc.

The Cloud Service Offering (to include cloud region or datacenter) must be detailed in the TOE evaluated configuration details. CSOs can not inherently be assumed to be equivalent. For instance, CSPs may have separate environments between government or commercial customers. However, if existing cloud authorizations exist for multiple regions or datacenters this may inform equivalency claims. Especially if the Trusted Platform meets the assumptions and objectives of the PP and is consistent across multiple cloud regions.

**Comment by bharveyTX** [comment]
Incorporated into introductory section
