### ISSUE TITLE
Minor feedback/suggestions.

### ISSUE THREAD

**Issue by tstodart** [CC-in-the-Cloud/Admin#37]
Preface
"Such cloud environments may or may not conform to hybrid, public, or private cloud topologies and the associated Cloud Service Providers." Not quite sure the purpose of this sentence , and the link between the topologies list and 'associated Cloud Service Providers' is unclear - propose review and revise.

On-Premises (On-Prem)
Proposed definition: On-premises refers to IT infrastructure hardware and software applications that are hosted on-site at the customer. The customer has direct control of on-premises IT assets including security and upkeep, and the physical location. Traditionally, Common Criteria has assumed on-premises environments.

Architecture - Life-cycle presentation.
I am not sure if this section really contributes much (maybe someone else will expand). The Agile vs waterfall issue in CC has been around for a long time and not sure if it is a problem we should try to tackle here. Maybe move these to glossary? The only other reference to dev ops is under "Development Environment Sub-Process"

Cloud Sub-Processes
Development Environment Sub-process.
The 'Trusted Provider' material around Assumptions and Objectives for the Operating Environment could be merged into this section.

Security Target (TSS) Sub-Process
The 'Trusted Provider' material around SFRs etc could be merged here. It probably would be good to review each section of an ST/PP. Again, Trusted Provided document does this at a very high level so can be merged in.

**Comment by jgb1128** [comment]
Preface already revised.

On-Prem needs more work will make a sep issue. @jgb1128 do this later

Move architecture to parking lot to discuss down the line

Cloud Sub-Process: agree will add placeholder.

ST Sub Process Agree.

**Comment by jgb1128** [comment]
We decided to keep the sfr stuff with everything else instead of splitting them up

**Comment by jgb1128** [comment]
For On-Premises:  On-premises refers to IT infrastructure hardware and software applications that are administered on-site at the customer by the customer. The customer has direct control of on-premises IT assets including security, upkeep, and the physical location. Traditionally, Common Criteria has assumed on-premises environments.

There are existing cloud deployment models in which a CSP will deploy infrastructure locally within the customer's physical control as an extension of a Cloud Service. As the CSP maintains administrative control of the infrastructure this shall not be considered an "on-premises" model.

**Comment by bharveyTX** [comment]
All resolved, closing.
