### ISSUE TITLE
Contributors Roles in Product Evaluations

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#46]
Sponsor (of the evaluation): This is the body responsible for requesting and usually financing an evaluation.

**Comment by mbdowne** [comment]
Derived in part from 5.2.2.6.e of CC Part 1 (CC:2022):

Sponsor: Entity responsible for requesting and supporting an evaluation

Do we want that to be entity or entities?

**Comment by mbdowne** [comment]
Decided to be: Any entity that is responsible for requesting and/or supporting an evaluation.

**Comment by jgb1128** [comment]
Closed in workshop.
