### ISSUE TITLE
Steps for adding "CC in the Cloud" to a PP

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#47]
One of the main tasks we need to do in the meeting is write down the process for adding CC in the Cloud testing to a PP.  We are executing one of those steps by mapping one of the PPs to FedRamp.  As I see it, the steps look something like this:

1. Review Guidance document and associated instructions
2. Map SFRs and SARs to the authorization scheme you wish to test on (FedRamp, C5, etc)
3. ID SFR "challenges" in a devops environment
4. Address challenges with new SFRs and/or determine if applicable
5. ID SAR "challenges with either new SAR's and/or determine if applicable
6. Edit cPP/PP and add new optional SFRs/SARs for cloud
7. Update supporting documents with new cloud requirements

This is very high level but I see a big chunk of our meetings dedicated to flowing this out

**Comment by jgb1128** [comment]
1. Review Guidance document and associated instructions
2. Map **Assumptions**, **Security Objections**, SFRs and SARs to the authorization scheme you wish to test on (FedRamp, C5, etc)
3. ID SFR "challenges" in a devops environment
4. Address challenges with new/updated SFRs and/or determine if applicable
5. ID SAR "challenges with either new/updated SAR's and/or determine if applicable
6. Edit cPP/PP and add new optional SFRs/SARs for cloud or selection based
7. Update cPPs supporting documents with new or modified evaluation activities

**Comment by jgb1128** [comment]
Added to guidance for review

**Comment by bharveyTX** [comment]
Added refinement to process. We added some structure so that the reference implementation (MDM example) can be further incorporated and shown as an example annex to other PPs so that cloud authorization schemes can see the mapping and endorse.

**Comment by jgb1128** [comment]
Team Justin just posted "[General Derivation Procedures](https://github.com/CC-in-the-Cloud/General/blob/Working/General%20Derivation%20Procedures_v3.1.docx)" for all of you to review.   These are the instructions to add CC in the Cloud to a PP

**Comment by bharveyTX** [comment]
Closing, will implement derivation guidance.
