### ISSUE TITLE
Labeling in Example Topology Diagrams

### ISSUE THREAD

**Issue by fahmed11** [CC-in-the-Cloud/Admin#50]
In Figures 1, 2, and 3 of the Main Guidance Doc, the use of SaaS Provider, PaaS provider, and IaaS provider, along with ‘Cloud Service Provider’ is a bit confusing. I guess we are trying to distinguish ‘Cloud Service Provider’ from ‘TOE Developer’ in each case. So shall we designate the upper part of these figures with simply ‘TOE Developer’ instead of SaaS Provider, PaaS provider, and IaaS provider?

**Comment by jgb1128** [comment]
Simplify diagrams.

**Comment by jgb1128** [comment]
Clean up the diagrams if we have time at the workshop

**Comment by bharveyTX** [comment]
Rename the diagrams to SaaS Compoistion Examples instead of topology

**Comment by bharveyTX** [comment]
Diagram changes implemented.
