### ISSUE TITLE
Title Page, Footnotes, Headers, Footers, References

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#51]
Need a title page. Should include the team's graphic.
[https://github.com/CC-in-the-Cloud/General/blob/Working/images/ccitc%20graphic.jpg](url)

Also please add a date footer

For consideration, a contributors page

**Comment by jgb1128** [comment]
Update date and version on front page

**Comment by bharveyTX** [comment]
Leaving open until contributors section is populated.

**Comment by jgb1128** [comment]
TC Roles
Authors
Contributors
Members of the TC

@jgb1128 to propose

**Comment by bharveyTX** [comment]
Closed. Will take corrections if needed.
