### ISSUE TITLE
Administrative corrections

### ISSUE THREAD

**Issue by mbdowne** [CC-in-the-Cloud/Admin#53]
Preface - ESR is already completed (not "is developing")
Glossary:
SaaS - remove first sentence, as the headline already spells that out (same with PaaS and IaaS)
"CSPs hardware" below the figure should be CSP's
PaaS - "GP_OS_PP" is not the short name for NIAP's PP. Presumably this and others will be defined in references
"applied to the existing TOE Boundary and Cloud Cloud Operating Environment" - duplicate word (also in IaaS)

**Comment by heimannrj** [comment]
PP_GPCP_V1.0

**Comment by jgb1128** [comment]
Closed.
