### ISSUE TITLE
Products vs Services

### ISSUE THREAD

**Issue by mbdowne** [CC-in-the-Cloud/Admin#54]
The Guidance document does not align with the terminology from the ESR, re: products. How is this going to be addressed? Is there some language clarifying the difference between the types of products/services that can be examined?

**Comment by mbdowne** [comment]
Now that some terms have been defined, need to make sure this is propagated throughout the document.

**Comment by heimannrj** [comment]
I believe we adopted the following definitions captured in Issue #48 

Product: Part of the equipment (hardware, software and materials) for which usability is to be specified or evaluated.
Source(s):
[NISTIR 8040](https://doi.org/10.6028/NIST.IR.8040) under Product from ISO 9241-11:1998

Service: A set of related IT components provided in support of one or more business processes.
Source(s):
NISTIR 7693 under Service

**Comment by bharveyTX** [comment]
We have revised the preface and included the relevant definitions. Closing per discussion on May 24th call.
