### ISSUE TITLE
Expanding the Evaluated Configuration

### ISSUE THREAD

**Issue by mbdowne** [CC-in-the-Cloud/Admin#57]
"additional TSS and Assurance Activities could be prescribed to expand the evaluated configuration in a Cloud Operating Environment" - expanded to what? Is there something else that it would cover? Expanded from a traditional software product? Should probably discuss how this environment differs from a traditional on-prem environment (unless that is covered later). Consider comparing the contents of Figure 1 to what is in software PPs (and directly copy the figure).

Note also that PaaS and IaaS also reference the Cloud Operating Environment above the figure, while SaaS references the TOE platform instead, but then talks about Cloud Operating Environment below Figure 1.

**Comment by jgb1128** [comment]
Closed this was removed. Can reopen if this becomes important.
