### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by mbdowne** [CC-in-the-Cloud/Admin#60]
From JIL Document:

Evaluator: "The evaluation laboratory that performs the evaluation work under a national scheme."

Certification Body: "An independent overseer that licenses national evaluation laboratories and issues the certificate based on the work of such laboratories." Note that JIL document also defines it as "Certification Body or Evaluation Authority"

**Comment by mbdowne** [comment]
From CC:2022 Part 1 for Evaluator:
individual assigned to perform evaluations in accordance with a given evaluation standard and 
associated evaluation methodology

**Comment by mbdowne** [comment]
From CC:2022 Part 1 for Evaluation Authority:
body operating an evaluation scheme

**Comment by jgb1128** [comment]
Closed in workshop.
