### ISSUE TITLE
Glossary - End User

### ISSUE THREAD

**Issue by mbdowne** [CC-in-the-Cloud/Admin#61]
The JIL document definition is specific to the technology: "The card user acting as operator of the smartcard TOE." Obviously we will need replacement language, and we may want to have multiple variations of this. Administrators, agencies, actual users? This might be spelled out instead by use care, or referenced from the various PPs. Similarly we should look at Issue #44 for TOE developer.

**Comment by jgb1128** [comment]
Should we change to "customer?"

**Comment by heimannrj** [comment]
Some user definitions from CCPART1 for consideration:
**external entity user** 
human technical system or one of its components interacting with the target of evaluation (TOE) (3.90) from outside of the TOE boundary

**authorized user** 
entity (3.36) who may, in accordance with the security functional requirements (SFRs) (3.78), perform an operation on the target of evaluation (TOE) (3.90)

**Comment by bharveyTX** [comment]
We have decided to remove references to "end users" in the guidance document and will not provide a definition.
