### ISSUE TITLE
Comments/suggestions

### ISSUE THREAD

**Issue by iadgovuser55** [CC-in-the-Cloud/Admin#62]
Main Document
Preface: 
This is copied straight from the ESR, suggest some rewording: The CC in the Cloud Technical Working Group (CCitC) published an ESR document to capture the fundamental requirements for evaluating IT products applicable to CC which operate in cloud environments. This guidance builds off of that to provide a framework for PP authors to use to determine what changes would need to be made for a TOE being evaluated against their PP to be evaluated when deployed in a cloud environment... 

Objective:
I’d recommend rewording to clarify the intent and audience of the paper. Possible re-write: The intent of this document is to provide Protection Profile (PP) authors with guidance to for how to supplement their PP’s with the necessary evaluation requirements for TOEs being deployed in the cloud. This guidance defines common cloud evaluation and certification terminology and identifies areas where evaluations in the cloud will likely differ from on-premises evaluations. Evaluators, certifiers, and end users of CC evaluated products in the cloud may also find this guidance useful as it explains the additional security considerations that must be made when products are deployed in a cloud environment. 

Life-cycle Presentation:
I don’t see much use for a discussion of different development life-cycles (Agile, waterfall, etc.). It seems to me like this section is intended to eventually discuss the issue of continuous evaluation in cloud environments. I propose possibly changing this to something to that effect with the subsections addressing differences for Iaas, PaaS, and SaaS. This could be something like the following: Cloud platforms are constantly being updated under the surface. While continuous evaluation requirements can address certifying some of these changes this is an ongoing concern in cloud evaluations. Depending on the deployment scenario the TOE developer may not be able to have knowledge or control of the exact platform version the TOE is running on. [then address PaaS vs IaaS vs SaaS]

**Comment by jgb1128** [comment]
Closing. We will not be touching the ESR.
