### ISSUE TITLE
CMVP certifications for CSP's

### ISSUE THREAD

**Issue by heimannrj** [CC-in-the-Cloud/Admin#63]
Looking at the NIST CSRC website, one can find CMVP certs for many CSPs including AWS, Azure, and OCI.  Some discussion around how these certs give us a solid foundation to define what trusted environment/platforms/providers are in terms of CC would be useful.  

See:
https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4177
https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4273 &
https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/details?product=15358

**Comment by bharveyTX** [comment]
This will be rolled into PP specific context, closing the issue for guidance doc.
