### ISSUE TITLE
CSFC and Leveraging the Platform

### ISSUE THREAD

**Issue by GallagherTom** [CC-in-the-Cloud/Admin#65]
If two cloud-based TOEs use the underlying cloud platform for crypto (or other features), this creates a problem if those solutions are intended to create independent components of a CSFC solution. While this problem is not unique to cloud, it is much less likely with on-prem solutions. I'm not sure if it is appropriate to try to address this issue in our guidance, but it may be worth raising awareness of the issue.

**Comment by awnissen** [comment]
This does not seem like something our group would handle.  Revisit in the future to see if there is some appropriate response.   Recommend closing.

**Comment by bharveyTX** [comment]
Closed, will reopen if applicable following initial publication and input from CSfC.
