### ISSUE TITLE
Guidance Section 3.5

### ISSUE THREAD

**Issue by GallagherTom** [CC-in-the-Cloud/Admin#67]
This section (at least the first part) seems like it would be more readable as a table or list. As is, it seems like we're trying to cover the different SAR classes.

**Comment by tstodart** [comment]
Which document is this comment for? I am having difficulty finding a section 3.5. Please see [https://github.com/CC-in-the-Cloud/General)/Offsite Review/](https://github.com/CC-in-the-Cloud/General/tree/Working/Offsite%20Review) for this list of documents.

**Comment by tstodart** [comment]
Found it. This is a formatting error. Will correct in 'live version'.
