### ISSUE TITLE
Appendix

### ISSUE THREAD

**Issue by GallagherTom** [CC-in-the-Cloud/Admin#68]
Section 4.2 and 4.4 are missing the intro paragraph that describes the use case

**Comment by tstodart** [comment]
Which document is this comment for? I am having difficulty finding a sections 4.2 and 4.4. Please see https://github.com/CC-in-the-Cloud/General/tree/Working/Offsite%20Review for this list of documents.

**Comment by tstodart** [comment]
I found the location after cross-checking with the old version. Neither of these PP's have use cases for cloud. I can add the section and put 'none' if preferred.
