### ISSUE TITLE
Reuse of FedRAMP evidence for CC

### ISSUE THREAD

**Issue by jfmyerrors** [CC-in-the-Cloud/Admin#70]
Does the proposal of reusing some FedRAMP evidence create an issue for the complying with ISO17025?  The NIAP acceptance/reliance upon CMVP retains a dependency on the work being performed under ISO17025.   Does that extend to FedRAMP?

**Comment by bharveyTX** [comment]
Reuse of FedRAMP evidence is implemented in the general derivation guidance. Closing issue.
