### ISSUE TITLE
Audience Clarification - Main Guidance and Guidelines for Optimising existing Protection Profiles

### ISSUE THREAD

**Issue by compgeeksquires** [CC-in-the-Cloud/Admin#72]
If the _Guidelines for Optimising existing Protection Profiles_ becomes part of the _Guidance for Cloud Evaluations Document_, then the audience for the latter will need to be expanded. 
Given that they serve two different audiences (Guidance for Cloud lists "evaluation sponsors and manufacturers, but it is also related to evaluators, certifiers and end users of this type of products."; Guidelines for Optimising is focused on iTCs/PP authors) they may need to stay separate documents.

**Comment by jgb1128** [comment]
Leave open for discussion.

**Comment by bharveyTX** [comment]
The main guidance document has included all audiences without need to spin off additional docs. Closing per discussion.
