### ISSUE TITLE
Scope of cloud operating environment claims

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#73]
@bharveyTX  do later

**Comment by bharveyTX** [comment]
We need to expand upon the concept that a TOE Developer/ST Author must define in their TOE Platforms what public cloud resources. For instance a TOE developer must claim Product Version X on Cloud Provider Y with Compute Resource Z. All mandatory SFRs must map to this Cloud OE. If the Cloud OE can not fulfill an SFR, then that Cloud OE can not be included in the evaluation as it is not an appropriate TOE Platform.
