### ISSUE TITLE
Execution Environment

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#78]
Need a definition.

**Comment by jgb1128** [comment]
Platform plus supporting IT is this the definition? Idea from Mike Grimm

**Comment by mbdowne** [comment]
There was also a proposal to change to hosting environment.

**Comment by e-newt** [comment]
From James Donndelinger --- FROM cc2022 PART 1 - Everything outside the TOE boundary belongs to the TOE operational environment. In the case where the TOE is part of an IT product the IT product can have non-TOE parts. Such non-TOE parts are also part of the operational environment of the TOE.
The ST shall describe assumptions and define security objectives for the operational environment which together with the security functionality provided by the TOE itself are necessary to mitigate the threats, and to enforce organizational security policies (OSPs).

**Comment by mbdowne** [comment]
This relates to the proposed definition of Trusted Platform: the underlying [execution OR hosting] environment for the TOE that is sufficient to meet the [assumptions and environmental security objectives OR operational environment] of the PPs and modules the TOE claims.

**Comment by jgb1128** [comment]
Closed. See other definitions that supersede this discussion
