### ISSUE TITLE
ESR comments

### ISSUE THREAD

**Issue by mmbarry** [CC-in-the-Cloud/Admin#8]
Roger's comments:

I noticed the word “convey” used twice where I thought it should be “converse”. But, technically, “convey” is correct usage, though not common.  I note that one of its obscure definitions was “to steal from”, not accepted usage now. 

I’ll reread (re-review?) it later. It seems to me (a sample size of One and thus statistically insignificant), on first read, to say too much for an ESR. 

Today, CC reflects a static point in time security evaluation methodology.
	Today, CC reflects a static point in time for security evaluation methodology. 

As the market moves to cloud-based solutions, ISO/IEC15408 should be adapted in order to provide security assurance for the cloud scenario.
	This makes it seem that changing 15408 is the only goal of the ESR and the TWG. We should add something ike “And developers of products, applications, and system to be evaluated and developers of cPP’s aimed at Cloud Use evaluations, will be to add or alter specific code or cPP content carefully to ensure evaluate-able code and cPP’s. This will require know what to add or alter.”

Use Case 1:  is centrally hosted.It is  is centrally hosted. It is

Static Analysis:  this detail often unknown  this detail is often unknown

**Comment by bharveyTX** [comment]
Feedback incorporated into 5/5 working session.
