### ISSUE TITLE
TOE Identification and Version

### ISSUE THREAD

**Issue by gnickells** [CC-in-the-Cloud/Admin#82]
What is acceptable for TOE identification/Version (eg. web application URL and date)? 
For some cloud TOE's a specific version or patch level may not be applicable or available based on the architecture (rolling versions/updates). How should security patches be tracked in cloud TOE's?

**Comment by bharveyTX** [comment]
The tested configuration should be identified per usual CC requirements with respect to the applicable scheme requirements. This includes IT entities in the Cloud OE that are required by the TSS/CC Guide such as NTP/SMTP/Syslog/etc.

For Cloud OE identification we want to include Datacenter details, VM or Bare metal configuration information, OS image version/build and all details for which are applicable to the TOE type.

For patch and/or security patch information we would expect this information in the ST for the TOE and not necessarily the OE as it will be under CSP responsibility.

Give several examples from existing public cloud infrastructure.

**Comment by aws-brad** [comment]
AWS Examples
![Screenshot 2023-05-10 at 10 58 35 AM](https://github.com/CC-in-the-Cloud/General/assets/11507942/545f8dce-8469-44f7-938f-94234beeb5eb)
![Screenshot 2023-05-10 at 10 58 42 AM](https://github.com/CC-in-the-Cloud/General/assets/11507942/286a164c-f745-4a89-9957-79131638c084)
![Screenshot 2023-05-10 at 10 58 49 AM](https://github.com/CC-in-the-Cloud/General/assets/11507942/7cc1fcae-8d5e-4ee3-9bad-3bf0a5721ba1)

**Comment by bharveyTX** [comment]
Added new section for TOE identification in guidance doc. We still need to add the appropriate images, captions, and explanations.

**Comment by bharveyTX** [comment]
We reviewed the completed section on the 8/23/23 call and have no further additions. Closing the issue and marking complete.
