### ISSUE TITLE
NIAP Policy 5 - CAVP OE Listing

### ISSUE THREAD

**Issue by gnickells** [CC-in-the-Cloud/Admin#83]
The underlying hardware in a cloud environment may not be known or available to a Vendor, even moreso the specific CPU information. Clarification on what detail would/should reasonably be expected of a vendor that does not have intimate knowledge of the underlying cloud infrastructure (when obtaining CAVP).

**Comment by bharveyTX** [comment]
Added new section in intro concerning OE details and labeling expectations.
