### ISSUE TITLE
Consider Removal of Trusted Provider from ESR

### ISSUE THREAD

**Issue by jgs1618** [CC-in-the-Cloud/Admin#84]
FedRAMP uses the term FedRAMP Authorized for a Cloud Service Offering.  From the FAQs, "A Cloud Service Provider (CSP) goes through the authorization process once, and after achieving an authorization for their Cloud Service Offering (CSO), the security package can be reused by any federal agency."

FedRAMP creates transparent standards and processes for security authorizations.

FedRAMP does not have a concept of Trusted Provider.

**Comment by jgb1128** [comment]
@jgs1618 please provide a reference for this quote.

**Comment by jgs1618** [comment]
@jgb1128 - https://www.fedramp.gov/faqs/  
Under General - "What is FedRAMP's value to the federal government?"

**Comment by bharveyTX** [comment]
Closing per issue #33. Will remove from ESR if updated in the future.
