### ISSUE TITLE
Trusted Platform Definition needs hosting or executional environment defined 

### ISSUE THREAD

**Issue by jgs1618** [CC-in-the-Cloud/Admin#86]
Trusted Platform Definition agreed upon by Trusted Platform Group Workshop Day 3 before lunch.  When the Main Guidance doc group returned, they had different thoughts about this definition - there was no longer agreement.  It is possible it would need a vote. 

Trusted Platform definition:  Trusted platform is the underlying hosting environment for the TOE that is sufficient to meet the assumptions and environmental security objectives of the PPs and modules the TOE claims. (Note: We need to define executional environment - which has now been changed to hosting environment).
o	The certificate authorizing scheme determines sufficiency by publishing a policy.
o	Components of a platform may include, e.g., an operating system, virtualization hypervisor, various switches, and the hardware needed to run the software.

**Comment by jgb1128** [comment]
This is now resolved.
