### ISSUE TITLE
Trusted Platform Definition (see issue #86) requires acceptance or vote

### ISSUE THREAD

**Issue by jgs1618** [CC-in-the-Cloud/Admin#87]
Issue #86 notes pasted here:

Trusted Platform Definition agreed upon by Trusted Platform Group Workshop Day 3 before lunch. When the Main Guidance doc group returned, they had different thoughts about this definition - there was no longer agreement. It is possible it would need a vote.

Trusted Platform definition: Trusted platform is the underlying hosting environment for the TOE that is sufficient to meet the assumptions and environmental security objectives of the PPs and modules the TOE claims. (Note: We need to define execution environment - which has now been changed to hosting environment).
o The certificate authorizing scheme determines sufficiency by publishing a policy.
o Components of a platform may include, e.g., an operating system, virtualization hypervisor, various switches, and the hardware needed to run the software.

**Comment by jgs1618** [comment]
See Workshop Materials/February 2023 Workshop/Workshop-Trusted Platform/20230209-Day3-Trusted Platform-Provider Summary,docx
https://github.com/CC-in-the-Cloud/General/blob/Working/Workshop%20Materials/Feburary%202023%20Workshop/Workshop-Trusted%20Platform/20230209-Day3-Trusted%20Platform-Provider%20Summary.docx

**Comment by jgb1128** [comment]
Trusted platforms will be constantly changing. The labs will provide an assessment based on the schemes policies. The guidelines will provide guidance to the schemes and PP authors about how to evaluate products in the cloud and recommended criteria for trusted platforms. Schemes can modify as they see fit via policies (published or not).

**Comment by jgb1128** [comment]
Trusted Platform definition: Trusted platform is the underlying hosting environment for the TOE that is sufficient to meet the assumptions and environmental security objectives of the PPs and modules the TOE claims.  
o The certificate authorizing scheme determines sufficiency by publishing a policy.
o Components of a platform may include, e.g., an operating system, virtualization hypervisor, various switches, and the hardware needed to run the software.

**Comment by GY5318** [comment]
I am okay with it is and do not see a need for a vote.

**Comment by tstodart** [comment]
"The certificate authorizing scheme determines sufficiency by publishing a policy." Is this sentence mandating that any scheme must have published a policy prior to evaluation? Is there are need for this to be mandatory or can we soften this?
e.g. "The certificate authorizing scheme determines sufficiency and may publish a policy"?

**Comment by jgb1128** [comment]
@tstodart this is a good point and a minor change that may make it more palatable to some schemes.

**Comment by GallagherTom** [comment]
Recommend one small change to the second bullet:
- "various switches" sounds informal and doesn't match the tone of the prior text. Recommend changing "various switches" to "network components" or "switches"

Recommendation for discussion:
Potentially add the following bullet "The Trusted Platform should be distinct from the TOE". The logic here is that you can't evaluate a part of the Trusted Platform as the TOE while claiming that it is on a Trusted Platform. I see this potentially being an issue with SaaS.

**Comment by jgb1128** [comment]
Trusted Platform definition FINAL: Trusted platform is the underlying hosting environment for the TOE that is sufficient to meet the assumptions and environmental security objectives of the PPs and modules the TOE claims.
o The certificate authorizing scheme determines sufficiency **_and may publish a policy_**.
o Components of a platform may include, e.g., an operating system, virtualization hypervisor, **_network components or switches_**, and the hardware needed to run the software.

Note for the instructions on HOW to use the Trusted Platform we need to say that the trusted platform shall be distinct from the TOE.
