### ISSUE TITLE
Define Hosting Environment

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#88]
_Italics_ are modifications

Proposed: [Hosting Environment](https://www.lawinsider.com/dictionary/hosting-environment) means the hardware, operating system, management environment and computing resources _(including switches and routers_) _necessary_ for the running of the Software.

Common themes:
e.g., an operating system, virtualization hypervisor, various switches, trusted administrators, and the physical security for all required components.

**Comment by heimannrj** [comment]
Articulating what the hardware is for any given cloud environment might be difficult to do consistently over time.  AWS offers "instances" or virtual server configurations that capture the processor type/class.  This might offer a more direct mapping to a CAVP certificate.  

Proposed change:
[Hosting Environment](https://www.lawinsider.com/dictionary/hosting-environment) means the [generic term for 'instance(s)'], operating system, management environment and computing resources (including switches and routers) necessary for the running of the Software.

**Comment by fahmed11** [comment]
Is the above definition more targeted for the SaaS use case? Can we generalize by phrasing as follows?
Hosting Environment means the hardware, operating system, and/or computing resources and management environment  necessary for the running of the cloud-based product.

**Comment by jgb1128** [comment]
Remove execution environment from Main doc @bharveyTX 

FINAL: Hosting Environment consists of everything that is outside the TOE boundary and is equivalent to the CC term "Operational Environment."

**Comment by jgb1128** [comment]
Revisit if not specific enough for requirements.
