### ISSUE TITLE
Perhaps a definition of Cloud Services might be useful in the Guidance Document

### ISSUE THREAD

**Issue by jgs1618** [CC-in-the-Cloud/Admin#91]
Under #54 the following definition is stated:
 in Issue https://github.com/CC-in-the-Cloud/General/issues/48

Service: A set of related IT components provided in support of one or more business processes.
Source(s):
NISTIR 7693 under Service

RedHat defines Cloud Services as: "Cloud services are infrastructure, platforms, or software that are hosted by third-party providers and made available to users through the internet. "

https://www.redhat.com/en/topics/cloud-computing/what-are-cloud-services#:~:text=Cloud%20services%20are%20infrastructure%2C%20platforms,to%20users%20through%20the%20internet.

Perhaps some definition of Cloud Services would also be useful in that section.

**Comment by fahmed11** [comment]
Cloud Security Alliance blog has this description of Cloud Service, in defining a CSP: 
“A Cloud Service is any system that provides on-demand availability of computer system resources, e.g; data storage and computing power, without direct active management by the user”. 
https://cloudsecurityalliance.org/blog/2020/04/30/what-is-a-cloud-service-provider/

**Comment by heimannrj** [comment]
The following text from NIST may be helpful in setting the context for the definition of CSP for CCitC.  Emphasis mine.

From NIST.SP.800-12r1 (Section 2.2):
"When an organization's information and systems are linked with external systems, management's responsibilities extend beyond organizational boundaries. This may require that management (1) know what general level or type of security is employed on the external system(s), and/or (2) seek assurance that the external system provides adequate security for the organization’s information and system. For example, **_cloud service providers (CSPs) and cloud supply chain participants may assume the management role for storing, processing, and transmitting organizational information._** However, that does not leave the organization free of any security related responsibility. It is up to the organization to ensure that the CSPs and cloud supply chain participants provide an appropriate level of security for the information being stored, processed, and transmitted."

**Comment by jgb1128** [comment]
Definition proposed: "A Cloud Service is any system that provides on-demand availability of computer system resources, e.g; data storage and computing power, without direct active management by the user." https://cloudsecurityalliance.org/blog/2020/04/30/what-is-a-cloud-service-provider/
ADD to Main Doc in Glossary.  Cross reference that the scope of this initial project is to NOT evaluate cloud services.
