### ISSUE TITLE
Definition of Cloud Authorization Scheme

### ISSUE THREAD

**Issue by jgb1128** [CC-in-the-Cloud/Admin#93]
Need a definition.  Seems to be the group that authorizes a cloud service for use in government aka the JAB.  Someone needs to see if FedRamp or CSA has a definition. https://www.fedramp.gov/governance/

A regulatory body or entity that authorizes cloud service offerings for use by their respective governmental agencies or regulated industries.

Of note:  The term “authorisation scheme” encompasses any procedure under which a provider or a recipient is in effect required to obtain from a competent authority a formal decision, or an implied decision, concerning access to a service activity, or the exercise thereof.  https://lawlegal.edu/authorisation-schemes

**Comment by fahmed11** [comment]
The way I understand is-- FedRAMP, C5 (in Germany) are examples of Cloud Authorization scheme. FedRAMP homepage describes itself as "The Federal Risk and Authorization Management Program (FedRAMP®) provides a standardized approach to security authorizations for Cloud Service Offerings." JAB is one of the two approaches FedRAMP uses for authorization; the other one being Agency authorization.
https://www.fedramp.gov/jab-authorization/
https://www.fedramp.gov/agency-authorization/

**Comment by jgb1128** [comment]
Proposed: "A regulatory body or entity that authorizes cloud service offerings for use by their respective governmental agencies or regulated industries."
